# Generated by Django 5.1.4 on 2024-12-23 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_comments_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='report',
            field=models.PositiveSmallIntegerField(choices=[(1, 'None'), (2, 'Bulying or unwanted content'), (3, 'Suicide, self-injury'), (4, 'Nudity or sexual activity'), (4, 'Scam, fraud, false information')], default=None),
        ),
    ]
