# Generated by Django 5.1.4 on 2024-12-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_post_alter_comment_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='report',
            field=models.PositiveSmallIntegerField(choices=[(1, 'None'), (2, 'Bulying or unwanted content'), (3, 'Suicide, self-injury'), (4, 'Nudity or sexual activity'), (4, 'Scam, fraud, false information')], default=None, null=True),
        ),
    ]
